#pragma once

#define NUONUO_DEVICE_NAME "nuonuo-pet"
#define NUONUO_FIRMWARE_VERSION "0.1.0"
#define NUONUO_DEFAULT_MODEL "unknown"
#define NUONUO_HAS_DISPLAY 1
#define NUONUO_HAS_AUDIO 1
#define NUONUO_HAS_WIFI 1
#define NUONUO_BACKEND_BASE_URL "http://127.0.0.1:8000"
#define NUONUO_DEFAULT_PET_ID "demo-pet"
#define NUONUO_SYNC_INTERVAL_MS 15000

